version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: gunicorn manage_all:application --bind 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:80"
    depends_on:
      - db