version: '2'
services:
  db:
    image: postgres
    volumes:
      - /mnt/db_volume1/postgresdata/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: "sh run_web.sh"
    ports:
      - "80:8001"
    environment:
      - DB_TYPE=postgresql
    networks:
      - default
    links:
      - db
    volumes:
      - .:/code