version: '2'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - /mnt/db_volume1/postgresdata/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - int_net
  web:
    restart: always
    build: .
    command: "sh run_web.sh"
    ports:
      - "8001:8001"
    environment:
      - DB_TYPE=postgresql
    links:
      - db
    volumes:
      - .:/code
    networks:
      - int_net
      - default

networks:
  int_net:
