---

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "postgres-db-volume:/mnt/db-volume1/lib/postgresql/data/manage_all/"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn rmatemanage.wsgi:application --bind 0.0.0.0:8001 --workers 3
    volumes:
      - .:/code
    ports:
      - "8001:80"
    networks:
      - default
    links:
      - db

volumes:
  postgres-db-volume-ms:

networks:
  default: