version: '2'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - /mnt/db_volume1/postgresdata/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back_net
  web:
    restart: always
    build: .
    command: "sh run_web.sh"
    ports:
      - "80:8001"
    environment:
      - DB_TYPE=postgresql
    networks:
      - default
    links:
      - db
    volumes:
      - .:/code
    networks:
      - mid_net
      - back_net

networks:
  mid_net:
  back_net: